USE [Asesoratec]
GO
/****** Object:  Database [AsesoraTEC]    Script Date: 03/11/2024 01:18:26 p. m. ******/
CREATE DATABASE [AsesoraTEC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AsesoraTEC', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AsesoraTEC.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AsesoraTEC_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\AsesoraTEC_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [AsesoraTEC] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AsesoraTEC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AsesoraTEC] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AsesoraTEC] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AsesoraTEC] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AsesoraTEC] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AsesoraTEC] SET ARITHABORT OFF 
GO
ALTER DATABASE [AsesoraTEC] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AsesoraTEC] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AsesoraTEC] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AsesoraTEC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AsesoraTEC] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AsesoraTEC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AsesoraTEC] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AsesoraTEC] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AsesoraTEC] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AsesoraTEC] SET  ENABLE_BROKER 
GO
ALTER DATABASE [AsesoraTEC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AsesoraTEC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AsesoraTEC] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AsesoraTEC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AsesoraTEC] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AsesoraTEC] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AsesoraTEC] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AsesoraTEC] SET RECOVERY FULL 
GO
ALTER DATABASE [AsesoraTEC] SET  MULTI_USER 
GO
ALTER DATABASE [AsesoraTEC] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AsesoraTEC] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AsesoraTEC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AsesoraTEC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AsesoraTEC] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AsesoraTEC] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'AsesoraTEC', N'ON'
GO
ALTER DATABASE [AsesoraTEC] SET QUERY_STORE = ON
GO
ALTER DATABASE [AsesoraTEC] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [AsesoraTEC]
GO
/****** Object:  Table [dbo].[asesorias]    Script Date: 03/11/2024 01:18:26 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[asesorias](
	[id_asesoria] [int] IDENTITY(1,1) NOT NULL,
	[id_alumno] [int] NULL,
	[id_asesor] [int] NULL,
	[fecha] [date] NOT NULL,
	[hora] [time](7) NOT NULL,
	[tema] [nvarchar](255) NOT NULL,
	[estado] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_asesoria] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[asesorias_temas]    Script Date: 03/11/2024 01:18:26 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[asesorias_temas](
	[id_asesoria] [int] NOT NULL,
	[id_tema] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_asesoria] ASC,
	[id_tema] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[evaluaciones]    Script Date: 03/11/2024 01:18:26 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[evaluaciones](
	[id_evaluacion] [int] IDENTITY(1,1) NOT NULL,
	[id_asesoria] [int] NULL,
	[id_alumno] [int] NULL,
	[puntaje] [int] NULL,
	[comentarios] [nvarchar](max) NULL,
	[fecha_evaluacion] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_evaluacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[progreso_asesorias]    Script Date: 03/11/2024 01:18:26 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[progreso_asesorias](
	[id_progreso] [int] IDENTITY(1,1) NOT NULL,
	[id_alumno] [int] NULL,
	[total_asesorias] [int] NULL,
	[evaluacion_promedio] [decimal](4, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_progreso] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[temas]    Script Date: 03/11/2024 01:18:26 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[temas](
	[id_tema] [int] IDENTITY(1,1) NOT NULL,
	[nombre_tema] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_tema] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[usuarios]    Script Date: 03/11/2024 01:18:26 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[usuarios](
	[id_usuario] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [nvarchar](100) NOT NULL,
	[correo] [nvarchar](100) NOT NULL,
	[contrasena] [nvarchar](255) NOT NULL,
	[rol] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[correo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[asesorias] ADD  DEFAULT ('pendiente') FOR [estado]
GO
ALTER TABLE [dbo].[progreso_asesorias] ADD  DEFAULT ((0)) FOR [total_asesorias]
GO
ALTER TABLE [dbo].[progreso_asesorias] ADD  DEFAULT ((0)) FOR [evaluacion_promedio]
GO
ALTER TABLE [dbo].[asesorias]  WITH CHECK ADD FOREIGN KEY([id_alumno])
REFERENCES [dbo].[usuarios] ([id_usuario])
GO
ALTER TABLE [dbo].[asesorias]  WITH CHECK ADD FOREIGN KEY([id_asesor])
REFERENCES [dbo].[usuarios] ([id_usuario])
GO
ALTER TABLE [dbo].[asesorias_temas]  WITH CHECK ADD FOREIGN KEY([id_asesoria])
REFERENCES [dbo].[asesorias] ([id_asesoria])
GO
ALTER TABLE [dbo].[asesorias_temas]  WITH CHECK ADD FOREIGN KEY([id_tema])
REFERENCES [dbo].[temas] ([id_tema])
GO
ALTER TABLE [dbo].[evaluaciones]  WITH CHECK ADD FOREIGN KEY([id_alumno])
REFERENCES [dbo].[usuarios] ([id_usuario])
GO
ALTER TABLE [dbo].[evaluaciones]  WITH CHECK ADD FOREIGN KEY([id_asesoria])
REFERENCES [dbo].[asesorias] ([id_asesoria])
GO
ALTER TABLE [dbo].[progreso_asesorias]  WITH CHECK ADD FOREIGN KEY([id_alumno])
REFERENCES [dbo].[usuarios] ([id_usuario])
GO
ALTER TABLE [dbo].[asesorias]  WITH CHECK ADD CHECK  (([estado]='cancelada' OR [estado]='completada' OR [estado]='pendiente'))
GO
ALTER TABLE [dbo].[evaluaciones]  WITH CHECK ADD CHECK  (([puntaje]>=(1) AND [puntaje]<=(10)))
GO
ALTER TABLE [dbo].[usuarios]  WITH CHECK ADD CHECK  (([rol]='asesor' OR [rol]='alumno'))
GO
USE [master]
GO
ALTER DATABASE [AsesoraTEC] SET  READ_WRITE 
GO
